### ISSUE TITLE
Can one insert an empty page?

### ISSUE THREAD

**Issue by rtavenar** [liantze/cdcalendar#2]
Hi there,

Thank you for this awesome LaTeX class! 

I was wondering if there was any possibility to insert an empty page between two months, and if so, what command should one use to do so?

Best regards,
Romain

EDIT: for what it's worth, I have made the following tweak to fit my needs:

in `cdcalendar.cls`:

```latex
\newcommand\makeIllustrationOnlyPage[1]{%
  \begingroup%
    \begin{textblock*}{\paperwidth}(0pt,0pt)%
        \includegraphics[width=\paperwidth]{#1};
    \end{textblock*}
  \endgroup\null\clearpage\nopagecolor\normalsize%
}
```

in the main TeX file:

```latex
\makeIllustrationOnlyPage{my_full_page_image_that_comes_just_before_january}

\begin{monthCalendar}{2023}{01}

%%% events must be given AFTER \begin{monthCalendar}
%%% Currently you must give events on the same page
%%% as the monthly calendar.

%% This is an one-day event
\event[mark style=holiday]{2023-01-01}{}{New Year's Day}
%% This is a 5-day event
\event[mark style=blue icon,marker=\faBriefcase]{2023-01-30}{5}{ACME Conference}
%% you could also write \event{2023-01-06}{2023-02-03}{ACME Conference}

\end{monthCalendar}

```

**Comment by liantze** [comment]
I don't think it's necessary to update the .cls. You can do something like this in the .tex file:

```latex
...
\end{monthCalendar}

\clearpage
\ThisCenterWallPaper{1}{image-file-name} 
% look into wallpaper package documentation for more commands:
% https://texdoc.org/pkg/wallpaper
\clearpage

% for the next month
\illustration{...}
\begin{monthCalendar}{2023}{02}
...
```

Or, if you had wanted a "cover page", you can use `\coverImage` and `\makecover`: look at the lines just after `\begin{document}` on examples how to set these. Currently the `\makecover\clearpage` is commented out so no cover is generated. You can un-comment them to see the example cover page.
