### ISSUE TITLE
Setting all months to 30 days

### ISSUE THREAD

**Issue by thom-github** [liantze/cdcalendar#3]
Hi there,

I hope it's ok to create an issue for this here, I haven't found another means to contact you.

I'd like to create a calendar for a roleplaying game I'm running, and I'd like to have every month have 30 days. Is there a way to set this cdcalendar up for something like that?

**Comment by liantze** [comment]
Well, the TikZ calendar library works with ISO dates and the Gregorian calendar. I could be mistaken but I _think_ it won't work with non-Gregorian calendars.

**Comment by thom-github** [comment]
Right, yes, that makes sense. 
Thanks for the feedback, and for the really useful package. :)

**Comment by liantze** [comment]
You're welcome!
